kind: PersistentVolume
apiVersion: v1
metadata:
  name: log-pv-volume
  namespace: {NAMESPACE}
  labels:
    app: sbot-log
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: {MOUNT_PATH}
    server: {NFS_SERVER_IP}