kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: log-pv-claim
  namespace: {NAMESPACE}
  labels:
    app: sbot-log
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
